### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by Saalbuerger**
Whitout this, jicofi will Not start

### CODE REVIEW

**Comment by saghul** [comment]
This is no longer needed, master is now using client proxy connections instead of a component connection.

**Comment by Saalbuerger** [comment]
Yes, i now it but new install will not start. Only an error: FATAL ERROR: Jicofo auth password must be set'

- fresh install
- gen. Password 
- Docker-compose up -d
- docker restart whit error

**Comment by saghul** [comment]
You should not use master just like that. Use a release tag, which pins images to config.

Current master works with the unstable images.

**Comment by Saalbuerger** [comment]
Hi @saghul - i get it, thanks.

but the quick start Guide is now broken (the way i used it befor), only whit the last Part (Build Instruction) it will ne work.

**Pull request closed without merging**
