### PR TITLE
Add container_name attributes to docker-compose.yml

### PR DESCRIPTION
**Pull request by matthinc**
The container_name attribute makes it easier to reference a specific container when working with docker-commands.

### CODE REVIEW

**Comment by saghul** [comment]
Why do you need this? When using `docker-compose` you can already refer to them by their short name: `docker-compose logs web` for example.

**Comment by matthinc** [comment]
In my specific case: The monitoring system requires a container_name to check if all docker containers are running properly.
But I like the idea of container_name in general. It's very handy if you use `docker ps` or `docker stats` to get an overview of all docker containers on the current machine.

**Comment by debfx** [comment]
> It's very handy if you use docker ps or docker stats to get an overview of all docker containers on the current machine.

docker-compose automatically assigns readable container names. If you name the folder where docker-compose.yml is located `jitsi` it's `jitsi_web_1` for example.

> I just think there is no reason not to have it.

The downside is that you can't run multiple Jitsi instances on the same dockerd (think of test and prod instances).

**Comment by saghul** [comment]
> The downside is that you can't run multiple Jitsi instances on the same dockerd (think of test and prod instances).

Big enough of a downside indeed.

**Pull request closed without merging**
