### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by daaaaan**
Fixes incorrect documentation re : internal auth

Fixes : #226 #216

### CODE REVIEW

**Comment by saghul** [comment]
That used to work... what’s the difference between register and adduser?

**Comment by saghul** [comment]
Hum, the docs specify both work: https://prosody.im/doc/creating_accounts

Moreover we use register for creating internal accounts which are internally needed...

**Comment by vidschofelix** [comment]
`prosodyctl --config /config/prosody.cfg.lua register username meet.jitsi`
also works

**Comment by wojas** [comment]
Even if the `register` command actually works, this part of the README is incorrect for `register`:

> The command then asks for a password interactively.

It's also unclear that `username` and `password` in the example are placeholders, and that `meet.jitsi` is the default (or even hardcoded?) in the Docker Compose setup.

**Comment by saghul** [comment]
I tested this on a fresh install yesterday evening and it works just fine. Any chance you've made changes to the prosody setup?

**Comment by wojas** [comment]
The remark about "The command then asks for a password interactively." threw me off. With that extra line, it's not clear that `password` on the commandline is a placeholder, because why would you get prompted for a password if you just specified it?

The command also does not output anything, which makes it seem like it's not working, and does not appear in the list of commands in the help output.

When there are three PRs regarding this specific part of the README (this, #249 and #274), please accept that something is unclear about that part of the documentation.

**Comment by saghul** [comment]
Agreed, I'll fix the docs right away.

**Pull request closed without merging**
