### PR TITLE
Jigasi: Add configuration option to skip reinvite on focus change (fi…

### LINKED ISSUE #393: Jigasi interoperability problems with FreeSWITCH
In order to be able to interface Jigasi with FreeSWITCH for dial-in, setting the option 

```
net.java.sip.communicator.impl.protocol.sip.SKIP_REINVITE_ON_FOCUS_CHANGE_PROP=true
```

is required in order to get dial-in working (cf. https://community.jitsi.org/t/recently-updated-jigasi-and-jvb-jitsi-meet-incoming-calls-no-longer-get-answered/21182/24).

This is currently not possible with this Docker image.

It would be great if you could add support for this config switch.

### PR DESCRIPTION
**Pull request by ginkel**
…xes a compatibility issue with inbound calls via FreeSWITCH)

Fixes #393

### CODE REVIEW

**Comment by damencho** [comment]
This is already part of the code: https://github.com/jitsi/jigasi/commit/1658e409f977fde3321de18284340c15dfc71a82

**Comment by ginkel** [comment]
Interesting. I couldn't get it to work without manually setting the property to `true` in Jigasi's `sip-communicator.properties`.

**Comment by damencho** [comment]
I think maybe we havn't pushed jigasi to stable for a while and the docker is behind on versions.

**Comment by albe** [comment]
See also https://github.com/jitsi/docker-jitsi-meet/issues/339#issuecomment-609403144

Is a push to stable and update docker in the pipeline or anything blocking that?
I guess you're probably overwhelmed with new issue reports all over the places, which challenges your well known development workflow.

**Comment by saghul** [comment]
stable-4416 was just released. Please give it a test and holler if it doesn't work as expected.

**Comment by ginkel** [comment]
ACK, stable-4416 works like a charm w/o supplying the config option. Thank you!

**Pull request closed without merging**
