### PR TITLE
Add setting for encoded transform support

### PR DESCRIPTION
**Pull request by jan-di-cgm**
Add environment variable to configure `config.enableEncodedTransformSupport`

### CODE REVIEW

**Comment by saghul** [comment]
Are you aware of the fact that this doesn't work 100% well yet?

**Comment by jan-di-cgm** [comment]
Yes, we know that the feature is currently experimental. Our developers would like to test e2ee in production like environments.

**Comment by saghul** [comment]
I see. You can also enable it with a config-custom.js file, would that work for you?

**Comment by jan-di-cgm** [comment]
Yes, that is actually how we currently doing it. We extending the official images, where the `-custom` files are built via environment variables. This works - but as those are mostly generic settings, I would like to contribute them to the official image.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Sorry, can you rebase please?

**Pull request closed without merging**
