### PR TITLE
✨ Env var to setup STUN/TURN

### LINKED ISSUE #820: .ENV variable for useStunTurn: true, and STUN Server
Hello,

Can we have .ENV Variable for useStunTurn: true, and STUN Server in config.js?

Need for TURN Server active in P2P.

Other option is to mount out config.js. Because after reboot custom changes lost.

Or can I build own variables .ENV?

### PR DESCRIPTION
**Pull request by madmath03**
:sparkles: Env var to setup STUN/TURN to close #820

Signed-off-by: mathieu.brunot <mathieu.brunot@monogramm.io>

### CODE REVIEW

**Comment by madmath03** [comment]
@saghul I believe this might be useful for anyone who wishes to configure STUN/TURN for Jitsi throough env var:

```
ENABLE_STUN_TURN=1
ENABLE_P2P_STUN_TURN=1
P2P_STUN_SERVERS=stun:stun1.example.com:5349,stun:stun2.example.com:5349
```

**Comment by goacid** [comment]
https://github.com/jitsi/docker-jitsi-meet/pull/667

**Comment by saghul** [comment]
`ENABLE_STUN_TURN` is no longer necessary, internally it now defaults to `true`, we removed the setting.

**Comment by saghul** [comment]
Ping?

**Comment by saghul** [comment]
No follow-up, closing.

**Pull request closed without merging**
