### PR TITLE
Added related but missing part to quickstart

### PR DESCRIPTION
**Pull request by prodigy7**
As suggested in #304 documentation supplemented by missing part.

### CODE REVIEW

**Comment by saghul** [comment]
That is not necessary. Only if you want to build youir own images, which not everyone needs to. I'd be happy to have a section with "Build your own images" as a title though.

**Comment by prodigy7** [comment]
I followed first your quickstart, post my logs and everytime you said to me, that my versions are outdated. I pulled again and again but first when you told me, I'd to call "make clean && make" I got a current version. So, whats wrong? ;-)

**Comment by sgumirov** [comment]
I agree with Sagul, no need for "make". The current quickstart is actually correct, works just fine.

**Comment by prodigy7** [comment]
Okay. But then tell me, why I had a outdated Installation on my System where I had never fetched jitsi docker before? What was wrong? Only after execute make, all was on a current Version.

**Comment by sgumirov** [comment]
@prodigy7 Most probably dockerhub repo image is not updated instantly as currently no version tag is used to fetch specific container image version. 
With running `make build` you effectively build image locally and local docker repo has higher priority over dockerhub, so the newer version is used instead seamlessly later on.

**Pull request closed without merging**
