### PR TITLE
added bind_adress because of reverse proxy

### PR DESCRIPTION
**Pull request by BlackWolfDEsign**
only changes for reverse proxy setups

added:
HTTP_BIND and HTTPS_BIND

### CODE REVIEW

**Comment by saghul** [comment]
Can you please explain why this is needed?

**Comment by BlackWolfDEsign** [comment]
container binded to 0.0.0.0 = container reachable from the internet: container --> www
binded to 127.0.0.1 = only reachable from server: container --> server(reverse proxy) --> www

**Comment by saghul** [comment]
I still don’t get it, sorry. By default we bind on any interface and then expose the port with Docker. Are you using host mode or something?

**Comment by BlackWolfDEsign** [comment]
No, I just pulled jitsi-meet and started it. (without hostmode or something)

Without a binding address, jitsi-meet is bound to every interface and can therefore be reached via [IP]:PORT, **as you wrote**. 

But I want to bind to a fixed interface, and that was the easiest way (for me). Then i can map the [IP]:PORT to jitsi.domain.de and jitsi is only reachable via this address.

**Comment by saghul** [comment]
Ah I think I get it now. I’d like some changes though:

- A single option used in both cases
- Please call it HTTP_INTERFACE

**Comment by saghul** [comment]
Did you intend to close this?

**Pull request closed without merging**
