### PR TITLE
chore: add opencontainers labels to Dockerfiles

### PR DESCRIPTION
**Pull request by xoxys**
Fixes: https://github.com/jitsi/docker-jitsi-meet/issues/1216

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Cheers!

**Comment by rcarmo** [comment]
Hi there! I'd just like to let you know that the labels broke the Dockerfiles for Ubuntu 20.04 LTS when using Ubuntu's pre-packaged Docker, since they have spaces in them (I'm pretty sure you need quotation marks, although all of my LABELs are generated automatically, so I have only come across this when using the latest commit). I had to run:

```
sed -I "/^LABEL/d" $(find . -print |grep Dockerfile)
```

...to remove them in place, which was easiest when doing my own build.

**Comment by xoxys** [comment]
Hi @rcarmo good point! I never run into an issue while using labels without quotes, so it looks like they have "fixed" it on later docker versions... Nevertheless, should be easy to fix, sorry for the issue.

**Comment by xoxys** [comment]
I've created a PR to add quotes around the label values.

**Comment by saghul** [comment]
Thank you both!

**Pull request merged**
