### PR TITLE
WIP: OpenShift Support

### LINKED ISSUE #120: expose containers to OpenShift
Hi,

I am trying to run jitsimeet on Openshift. Since I couldn't find an image for Openshift platform, I'm trying to load the jitsi/docker-jitsi-meet containers for the Openshift platform. Could help?

At the time of prosody container loading, the /config/data owner folder is root instead of prosody, making it impossible to create certificates.

Docker Platform /config/...
drwxr-xr-x 2 root    root    4096 Jul 15 16:58 certs
drwxr-xr-x 2 root    root    4096 Jul 11 11:32 conf.d
drwxrwxrwx 3 prosody prosody 4096 Jul 18 10:30 data
-rw-r--r-- 1 root    root    6280 Jul 11 11:32 prosody.cfg.lua

Openshift Platform /config/...
drwxr-xr-x. 2 root root    6 Jul 18 14:03 certs
drwxr-xr-x. 2 root root   32 Jul 18 14:03 conf.d
drwxrwxrwx. 3 root root   52 Jul 18 14:03 data
-rw-r--r--. 1 root root 6280 Jul 18 14:03 prosody.cfg.lua

Openshift Platform prosody container Log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
The directory /config/data is not owned by the current user, won't be able to write files to it
The directory /config/data is not owned by the current user, won't be able to write files to it
mv: cannot stat '/config/data/*.crt': No such file or directory
mv: cannot stat '/config/data/*.key': No such file or directory
[cont-init.d] 10-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
startup             info	Hello and welcome to Prosody version 0.11.2
startup             info	Prosody is using the select backend for connection handling
certmanager         error	SSL/TLS: Failed to load '/config/certs/meet.jitsi.key': Check that the path is correct, and the file exists. (for meet.jitsi)
meet.jitsi:tls      error	Error creating context for c2s: error loading private key (No such file or directory)

### PR DESCRIPTION
**Pull request by sapkra**
@lsytnik @saghul Fixes #120 

I'm using Jitsi with OpenShift for some time and I'm ready to contribute my change now.

The problem with these Dockerfiles are that they are running as root which is not allowed in OpenShift for security reasons. One big problem while fixing the permissions are always the supervisor tools they are always running as root and are really hard to fix - so I had to add some workarounds. I hope we can get rid of s6 in the future but this is just my opinion.

I would appreciate if someone is able to test the changes with docker-compose and OpenShift and can provide some feedback.

My environment:
OpenShift/OKD 3.11

TODO
- [ ] Make it possible to use Let'sEncrypt with cronjobs
- [ ] Check if etherpad is working

### CODE REVIEW

**Comment by lsytnik** [comment]
Sapkra, could you please describe step-by-step the process to load these template directly to openshift?

I'm using  the same version of OpenShift v3.11

**Comment by saghul** [comment]
@lsytnik He was already very generous putting this up upon your request. You should be looking into that yourself.

**Comment by sapkra** [comment]
I just did it with the Web Console by just copy&paste the content of the jitisi.yaml, click next to process the image and just enter your Domain where jitsi should be running on. But you have to build the docker images yourself.

**Comment by lsytnik** [comment]
Sapkra, I had some problems to build docker images.

- Run the script fix-permissions.sh

Error:
Step 4/6 : RUN /fix-permissions.sh
 ---> Running in 5fc2141f7603
/bin/sh: 1: /fix-permissions.sh: not found

Workaround:
Copy the script fix-permissions.sh to folders ../jicofo/rootfs/, ../web/rpptfs/, ...


- Prosody Dockerfile - Proxy problem

I can't install the packages cyrussasl, lua-cjson and luajwtjitsi with luarocks. Some problem with proxy configuration

Installing https://luarocks.org/cyrussasl-1.1.0-1.rockspec
Cloning into 'lua-cyrussasl'...
fatal: unable to connect to github.com:
github.com[0: 140.82.114.4]: errno=Connection timed out
Error: Failed cloning git repository.

Workaround: 
Skip the instalation of these packages



- After build docker images I found the following errors in the docker prosody log file:

{"log":"[s6-init] making user provided files available at /var/run/s6/etc...exited 0.\n","stream":"stdout","time":"2019-07-29T17:15:49.646964779Z"}
{"log":"s6-chown: fatal: unable to chown /var/run/s6/etc/cont-init.d/01-set-timezone: Operation not permitted\n","stream":"stderr","time":"2019-07-29T17:15:49.743878028Z"}
{"log":"s6-chown: fatal: unable to chown /var/run/s6/etc/cont-init.d/10-config: Operation not permitted\n","stream":"stderr","time":"2019-07-29T17:15:49.743911608Z"}
{"log":"s6-chmod: fatal: unable to change mode of /var/run/s6/etc/cont-init.d/01-set-timezone: Operation not permitted\n","stream":"stderr","time":"2019-07-29T17:15:49.743919078Z"}
{"log":"s6-chmod: fatal: unable to change mode of /var/run/s6/etc/cont-init.d/10-config: Operation not permitted\n","stream":"stderr","time":"2019-07-29T17:15:49.743926027Z"}
{"log":"s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/10-saslauthd/run: Operation not permitted\n","stream":"stderr","time":"2019-07-29T17:15:49.830395774Z"}
{"log":"s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/prosody/run: Operation not permitted\n","stream":"stderr","time":"2019-07-29T17:15:49.830429537Z"}
{"log":"s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/10-saslauthd/run: Operation not permitted\n","stream":"stderr","time":"2019-07-29T17:15:49.830437506Z"}
{"log":"s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/prosody/run: Operation not permitted\n","stream":"stderr","time":"2019-07-29T17:15:49.830444681Z"}
{"log":"[s6-init] ensuring user provided files have correct perms...exited 0.\n","stream":"stdout","time":"2019-07-29T17:15:49.882506288Z"}
{"log":"[fix-attrs.d] applying ownership \u0026 permissions fixes...\n","stream":"stdout","time":"2019-07-29T17:15:49.882516566Z"}
{"log":"[fix-attrs.d] done.\n","stream":"stdout","time":"2019-07-29T17:15:49.882523187Z"}
{"log":"[cont-init.d] executing container initialization scripts...\n","stream":"stdout","time":"2019-07-29T17:15:49.882529414Z"}
{"log":"[cont-init.d] 01-set-timezone: executing... \n","stream":"stdout","time":"2019-07-29T17:15:49.882535859Z"}
{"log":"foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/01-set-timezone: Permission denied\n","stream":"stderr","time":"2019-07-29T17:15:49.882551402Z"}
{"log":"foreground: fatal: unable to wait for /var/run/s6/etc/cont-init.d/01-set-timezone: No child process\n","stream":"stderr","time":"2019-07-29T17:15:49.882558462Z"}

**Comment by lsytnik** [comment]
After building the base and base-java image, we ran docker-compose to create the other containers (web, prosody, jicofo and jvb). Searching prosody log file found some problems

{"log":"[s6-init] making user provided files available at /var/run/s6/etc...exited 0.\n","stream":"stdout","time":"2019-07-30T11:03:30.875168538Z"}
{"log":"[s6-init] ensuring user provided files have correct perms...exited 0.\n","stream":"stdout","time":"2019-07-30T11:03:31.121556258Z"}
{"log":"[fix-attrs.d] applying ownership \u0026 permissions fixes...\n","stream":"stdout","time":"2019-07-30T11:03:31.138109338Z"}
{"log":"[fix-attrs.d] done.\n","stream":"stdout","time":"2019-07-30T11:03:31.146079427Z"}
{"log":"[cont-init.d] executing container initialization scripts...\n","stream":"stdout","time":"2019-07-30T11:03:31.146092707Z"}
{"log":"[cont-init.d] 01-set-timezone: executing... \n","stream":"stdout","time":"2019-07-30T11:03:31.166174377Z"}
{"log":"[cont-init.d] 01-set-timezone: exited 0.\n","stream":"stdout","time":"2019-07-30T11:03:31.205851931Z"}
{"log":"[cont-init.d] 10-config: executing... \n","stream":"stdout","time":"2019-07-30T11:03:31.205985934Z"}
{"log":"cp: cannot create regular file '/config/saslauthd.conf': Permission denied\n","stream":"stderr","time":"2019-07-30T11:03:31.222078931Z"}
{"log":"fatal: unable to read from /config/saslauthd.conf, caused:\n","stream":"stderr","time":"2019-07-30T11:03:31.266110282Z"}
{"log":"\n","stream":"stderr","time":"2019-07-30T11:03:31.266155118Z"}
{"log":"   open /config/saslauthd.conf: no such file or directory\n","stream":"stderr","time":"2019-07-30T11:03:31.266162911Z"}
{"log":"\n","stream":"stderr","time":"2019-07-30T11:03:31.266169603Z"}
{"log":"mkdir: cannot create directory '/config/data': Permission denied\n","stream":"stderr","time":"2019-07-30T11:03:31.278103492Z"}
{"log":"cp: cannot create directory '/config/conf.d': Permission denied\n","stream":"stderr","time":"2019-07-30T11:03:31.302017996Z"}
{"log":"cp: cannot create regular file '/config/prosody.cfg.lua': Permission denied\n","stream":"stderr","time":"2019-07-30T11:03:31.302061758Z"}
{"log":"cp: cannot create regular file '/config/saslauthd.conf': Permission denied\n","stream":"stderr","time":"2019-07-30T11:03:31.302069283Z"}
{"log":"/var/run/s6/etc/cont-init.d/10-config: line 16: /config/conf.d/jitsi-meet.cfg.lua: No such file or directory\n","stream":"stderr","time":"2019-07-30T11:03:31.302076035Z"}
{"log":"\n","stream":"stdout","time":"2019-07-30T11:03:31.350080129Z"}
{"log":"\n","stream":"stdout","time":"2019-07-30T11:03:31.350125545Z"}
{"log":"**************************\n","stream":"stdout","time":"2019-07-30T11:03:31.350133238Z"}
{"log":"Prosody was unable to find the configuration file.\n","stream":"stdout","time":"2019-07-30T11:03:31.350139909Z"}
{"log":"We looked for: /etc/prosody//config/prosody.cfg.lua\n","stream":"stdout","time":"2019-07-30T11:03:31.350146444Z"}
{"log":"A sample config file is included in the Prosody download called prosody.cfg.lua.dist\n","stream":"stdout","time":"2019-07-30T11:03:31.350152885Z"}
{"log":"Copy or rename it to prosody.cfg.lua and edit as necessary.\n","stream":"stdout","time":"2019-07-30T11:03:31.350159448Z"}
{"log":"More help on configuring Prosody can be found at https://prosody.im/doc/configure\n","stream":"stdout","time":"2019-07-30T11:03:31.350165845Z"}
{"log":"Good luck!\n","stream":"stdout","time":"2019-07-30T11:03:31.350172247Z"}
{"log":"**************************\n","stream":"stdout","time":"2019-07-30T11:03:31.350178463Z"}
{"log":"\n","stream":"stdout","time":"2019-07-30T11:03:31.350184688Z"}
{"log":"\n","stream":"stdout","time":"2019-07-30T11:03:31.373996115Z"}
{"log":"\n","stream":"stdout","time":"2019-07-30T11:03:31.374038426Z"}

**Comment by sapkra** [comment]
Thanks for testing.
First of all I've cleaned up the your logs and then I started docker-compose the first time on this computer and the logs are looking good.
The problem can be that the old image has set the permissions to something you're not able to overwrite with the new default user. Can you try removing/cleanup you volumes and start the container again or checking the permissions of the directory inside the container?

Your logs:
```bash
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership \u0026 permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
cp: cannot create regular file '/config/saslauthd.conf': Permission denied
fatal: unable to read from /config/saslauthd.conf, caused:
 open /config/saslauthd.conf: no such file or directory
mkdir: cannot create directory '/config/data': Permission denied
cp: cannot create directory '/config/conf.d': Permission denied
cp: cannot create regular file '/config/prosody.cfg.lua': Permission denied
cp: cannot create regular file '/config/saslauthd.conf': Permission denied
/var/run/s6/etc/cont-init.d/10-config: line 16: /config/conf.d/jitsi-meet.cfg.lua: No such file or directory
Prosody was unable to find the configuration file.
We looked for: /etc/prosody//config/prosody.cfg.lua
A sample config file is included in the Prosody download called prosody.cfg.lua.dist
Copy or rename it to prosody.cfg.lua and edit as necessary.
More help on configuring Prosody can be found at https://prosody.im/doc/configure
Good luck!
```

My logs:
```bash
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
Generating RSA private key, 2048 bit long modulus
..................................+++++
....+++++
e is 65537 (0x010001)
Choose key size (2048): Key written to /config/data/meet.jitsi.key
Please provide details to include in the certificate config file.
Leave the field empty to use the default value or '.' to exclude the field.
countryName (GB): localityName (The Internet): organizationName (Your Organisation): organizationalUnitName (XMPP Department): commonName (meet.jitsi): emailAddress (xmpp@meet.jitsi): 
Config written to /config/data/meet.jitsi.cnf
Certificate written to /config/data/meet.jitsi.crt
2019-07-30T11:53:03.140708200Z 
Generating RSA private key, 2048 bit long modulus
.........................................................................+++++
.........................+++++
e is 65537 (0x010001)
Choose key size (2048): Key written to /config/data/auth.meet.jitsi.key
Please provide details to include in the certificate config file.
Leave the field empty to use the default value or '.' to exclude the field.
countryName (GB): localityName (The Internet): organizationName (Your Organisation): organizationalUnitName (XMPP Department): commonName (auth.meet.jitsi): emailAddress (xmpp@auth.meet.jitsi): 
Config written to /config/data/auth.meet.jitsi.cnf
Certificate written to /config/data/auth.meet.jitsi.crt
2019-07-30T11:53:03.303582300Z 
[cont-init.d] 10-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
saslauthd[247] :num_procs  : 5
saslauthd[247] :mech_option: /etc/saslauthd.conf
saslauthd[247] :run_path   : /var/run/saslauthd
saslauthd[247] :auth_mech  : ldap
saslauthd[247] :mmaped shared memory segment on file: /var/run/saslauthd/cache.mmap
saslauthd[247] :bucket size: 96 bytes
saslauthd[247] :stats size : 36 bytes
saslauthd[247] :timeout    : 28800 seconds
saslauthd[247] :cache table: 985828 total bytes
saslauthd[247] :cache table: 1711 slots
saslauthd[247] :cache table: 10266 buckets
saslauthd[247] :flock file opened at /var/run/saslauthd/cache.flock
saslauthd[247] :using accept lock file: /var/run/saslauthd/mux.accept
saslauthd[247] :master pid is: 0
saslauthd[247] :listening on socket: /var/run/saslauthd/mux
saslauthd[247] :using process model
saslauthd[247] :forked child: 264
saslauthd[264] :acquired accept lock
saslauthd[247] :forked child: 265
saslauthd[247] :forked child: 266
saslauthd[247] :forked child: 267
startup             info	Hello and welcome to Prosody version 0.11.2
startup             info	Prosody is using the select backend for connection handling
portmanager         info	Activated service 's2s' on [*]:5269, [::]:5269
portmanager         info	Activated service 'component' on [*]:5347
portmanager         info	Activated service 'c2s' on [*]:5222, [::]:5222
portmanager         info	Activated service 'legacy_ssl' on no ports
portmanager         info	Activated service 'http' on [*]:5280, [::]:5280
portmanager         info	Activated service 'https' on no ports
c2s55663fbca870     info	Client connected
jcp55663fbdf630     info	Incoming Jabber component connection
focus.meet.jitsi:component  info	External component successfully authenticated
c2s55663fbca870             info	Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
c2s55663fbca870             info	Authenticated as focus@auth.meet.jitsi
c2s55663fc57220             info	Client connected
c2s55663fc57220             info	Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
c2s55663fc57220             info	Authenticated as jvb@auth.meet.jitsi
```

**Comment by lsytnik** [comment]
Hi Sapkra,

The fix-permission scrit are changing the permission of /config to **1001** userid and inside docker prosody don't exist this userid. It's correctly?


fix-permissions.sh
chown 1001:0 -R /config /var/log /var/lib

Prosody's Docker
I have no name!@6662e6ce352b:/$ cd /config
I have no name!@6662e6ce352b:/config$ ls -la
total 8
drwxr-xr-x 2 root root 4096 Jul 30 15:58 .
drwxr-xr-x 1 root root 4096 Jul 30 16:52 ..
I have no name!@6662e6ce352b:/config$ cat /etc/passwd | grep 1001
I have no name!@6662e6ce352b:/config$ id 1001
id: '1001': no such user

**Comment by sapkra** [comment]
To have the user in the passwd file we have to manually add it like it's documented in the [OpenShift docs](https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines). But everything is working without it in all my environments so it's not necessary I guess.

You can run the following commands to see on which user you container is running on.
```bash
echo $UID
id -u
```

Your problem is that the permissions for the `/config` path are not right. It has to look like this if you are using a volume:
```bash
drwxr-xr-x 7 1001 root  224 Jul 30 13:53 .
drwxr-xr-x 1 root root 4096 Jul 30 13:53 ..
drwxr-xr-x 6 1001 root  192 Jul 30 13:53 certs
drwxr-xr-x 3 1001 root   96 Jul 30 13:53 conf.d
drwxrwx--- 5 1001 root  160 Jul 31 00:11 data
-rw-r--r-- 1 1001 root 6280 Jul 30 13:53 prosody.cfg.lua
-rw-r--r-- 1 1001 root  934 Jul 30 13:53 saslauthd.conf
```

The reason for this problem might be that you've started the actual dev branch before so it already has initialized the volume as root, then you've removed the content of the volume but not the volume itself. Now you are trying to run the container as 1001 but docker reuses the old volume with root permissions.

https://github.com/docker/compose/issues/3270#issuecomment-206425600
https://stackoverflow.com/questions/40462189/docker-compose-set-user-and-group-on-mounted-volume

@saghul Do you have an idea how to prevent this behavior? My plan would be to provide an migration guide because this seems like a breaking change.

**Comment by lsytnik** [comment]
Ok Sapkra, the UID is correctly.

I have no name!@6662e6ce352b:/$ echo $UID
1001
I have no name!@6662e6ce352b:/$ id -u
1001

I will investigate why it is starting as root.
Thank you.

**Comment by saghul** [comment]
Hey @sapkra I'm really sorry this has taken  so long. This project started as a side project (which then "graduated") and I haven't been able to keep up with all the good work that some contributors such as yourself have put our way. Apologies.

I just took a look and boy there are a lot of changes here!

So, in order to move this forward, here is what I propose:

- Split this PR into smaller PRs that just make the necessary permissions changes for OpenShift to work (those should be good for anyone, right?)
- Put the OpenShift code into some examples/OpenShift directory on a separate PR

I think this way we shouldbe able to do this quicker and everyone should be happy:

- You, because you'd hopefully not need to maintain a fork for the permissions stuff
- Us, because we get some nice fixes and examples for others to use
- Other users, because they'll have a quick way to start using this in OpenShift

WDYT?

**Comment by sapkra** [comment]
> I just took a look and boy there are a lot of changes here!
😅
 
> * Split this PR into smaller PRs that just make the necessary permissions changes for OpenShift to work (those should be good for anyone, right?)
Sounds good and it will just improve the security for everyone. But there are some differences between OpenShift and other platforms. OpenShift uses random UIDs and ignores  the `USER 1001` line of the Dockerfile. Everything I'm doing explicitly for the UID 1001 is just to remove some console warnings when running the containers outside of OpenShift.

> * Put the OpenShift code into some examples/OpenShift directory on a separate PR
Ok. Additionally I will add a `README.md` for the openshift example.

I hope to find some time in January to rebase and split this PR.

**Comment by saghul** [comment]
Sounds like a great plan, thanks a ton Paul!

**Comment by Bengrunt** [comment]
Hi there, I'm sorry but I'm quite new with Jitsi so maybe I'll ask a dumb question: why are the docker images based of Debian stretch and not buster, the current release? 

Kudos to you anyway, we got an Openshift platform and I'll try to deploy Jitsi following your guidelines ;)

**Comment by sapkra** [comment]
Closed in favor of #192 and #272.

**Pull request closed without merging**
