### PR TITLE
provide a deployment example for Kubernetes Kustomize

### PR DESCRIPTION
**Pull request by rsoika**
This is an example how to setup jitsi with Kubernetes Kustomize. 
It includes the base configuration and a description how custom settings and an Ingress can be applied

### CODE REVIEW

**Comment by rsoika** [comment]
Note that I created a new sub directory for kubernetes as mentioned by @prayagsingh 

https://github.com/jitsi/docker-jitsi-meet/pull/993#issuecomment-808181258

**Comment by saghul** [comment]
I think this should go into https://github.com/jitsi-contrib as a standalone repo. What do you think? I can add you to the org so you can create the repo and work on it there.

**Comment by rsoika** [comment]
of course. If you agree we can name the repo jitsi-contrib/kubernetes and bundle all kubernetes related stuff there

**Comment by saghul** [comment]
Looks like there are many ways to skin the cat :-) https://github.com/jitsi-contrib/meta/issues/2

**Comment by saghul** [comment]
Just invited you to the org @rsoika . Feel free to self-organize, try stuff out and see what's the best option going forward. IMHO starting with separate projects is a good start, there is always time to consolidate later.

**Pull request closed without merging**
