### PR TITLE
Maximize S/N ratio of env.example

### PR DESCRIPTION
**Pull request by frispete**
Here's a PR as being discussed. 

@saghul You might want to have a second look, please.

Advantages:
 * comments are consistent across the whole file now
 * easier to read/comprehend
 * spares 62 bytes :wink:

Disadvantages:
 * some churn for everybody (who diffs .env with this file, e.g. me)

I've documented the antidote for the latter issue in the commit message.
There's a chance, that people, who diff things, also read git logs. :smiley:

### CODE REVIEW

**Comment by saghul** [comment]
This is why I started adding periods:

```
- # A comma separated list of APIs to enable when the JVB is started. The default is none.
+ # A comma separated list of APIs to enable when the JVB is started. The default is none
```

I agree that when there is only one sentence it makes sense to drp it, but it doesn't when there is 2. So I added it everywhere for consistency and to keep my "OCD" at bay.

**Comment by frispete** [comment]
I would express it this way:
```
# A comma separated list of APIs to enable when the JVB is started [default: none]
```

**Comment by sapkra** [comment]
Wouldn't it make sense to remove the comments completely from the `.env` file? In my opinion, we don't need the docs for the variables in two places.

**Comment by frispete** [comment]
I think, they're useful, since it avoids switching between two documents, while mastering a pretty sophisticated setup (it still fails for me for some constellations, e.g. where the Android app is involved). It can and should be brief, of course.

**Pull request merged**
