### PR TITLE
[k8s] Remove files moved to template dir

### PR DESCRIPTION
**Pull request by gbonnefille**

### CODE REVIEW

**Comment by saghul** [comment]
Sorry, what?

**Comment by gbonnefille** [comment]
> Sorry, what?

I noticed that many YAML files are duplicated:
- in the `k8s` folder
- in the `k8s/templates` folder

IMHO, it is cleaner to remove the first ones.

**Comment by saghul** [comment]
Oh, I see. I'll let @aaronkvanmeerten review this one.

**Comment by sapkra** [comment]
Jitsi Helm lives now here: https://github.com/jitsi-contrib/jitsi-helm

**Pull request closed without merging**
