### PR TITLE
prosody: fix restart loop on rolling deployment

### PR DESCRIPTION
**Pull request by sapkra**

### CODE REVIEW

**Comment by saghul** [comment]
Cheers!

**Comment by saghul** [comment]
Hey @sapkra, I had to revert this, sorry. It breaks the default installation. Prosody fails to start because it cannot write to /tmp. I tried changing it to /var/run/ (which also makes more sense) but same thing, and I ran out of time for debugging.

**Comment by sapkra** [comment]
Mhh right...I have an idea how to fix it because I   had to change a lot of permissions anyway.

My suggestion:
I will update and split my OpenShift PR soon and we will apply this change afterwards or within the new PR which includes all permission changes.

**Comment by saghul** [comment]
Sounds good!

**Pull request merged**
