### PR TITLE
Add env variables for configuring videocodec

### PR DESCRIPTION
**Pull request by prayagsingh**
added env variables for configuring videocodecs

### CODE REVIEW

**Comment by cloudslash7** [comment]
Screen Shot 2021-05-16 at 11 20 17 PM

I'm still seeing VP8. It IS p2p, though. Could that be the problem?

**Comment by prayagsingh** [comment]
@saghul please review and let me know if you need any changes in env variables naming.

**Comment by saghul** [comment]
Thanks for doing this! I'd rather not have the ENABLE_VIDEOQUALITY flag and just apply the values all the time, IF set. This means we should not have defaults, at least for the bitrates. I can think of us changing the default in lib-jitsi-meet and then if a value is set apps wouldn't benefit of the new value.

**Comment by prayagsingh** [comment]
Thanks for the feedback @saghul 
I'll remove the default values.

**Comment by prayagsingh** [comment]
@saghul Please review.

**Comment by saghul** [comment]
Sorry I was on parental leave and forgot about this one. Did you intentionally close it?

**Comment by prayagsingh** [comment]
yes. Some of the commits were showing `ghost` username because of some issue in git-config(configured using a different email ID and this email ID doesn't exist on github). I will create a new PR with these changes only.

**Pull request closed without merging**
