### PR TITLE
Update GH action to also build for arm64

### LINKED ISSUE #1069: ARM64 Support for docker images
There are already many Jitsi related packages available for all arches, including arm64: https://download.jitsi.org/stable/

The whole docker stuff however still is only available for amd64, although there are already pretty powerful (and mostly cheaper) ARM64 Servers available on some cloud providers. Not to mention it would then also work on Raspberries (however don't know if they would be fast enough).

Can we somehow make the whole docker stuff also run on ARM64? There already was working version available on this fork, but since maintaining it alone without the community it's lacking behind a lot in terms of updates: https://github.com/amaumene/docker-jitsi-meet/

### PR DESCRIPTION
**Pull request by Firefishy**
Add arm64 build support. 
Add arm64 download logic in `Dockerfile`s

Closes #1069 #1214

### CODE REVIEW

**Comment by Firefishy** [comment]
`jibri` image uses chrome + chromedriver which do not appear to be available for `arm64` on linux. :-(

**Comment by adam-at-mobomo** [comment]
> `jibri` image uses chrome + chromedriver which do not appear to be available for `arm64` on linux. :-(

I believe chromium is available along with chromedriver support:

* https://vitux.com/debian-chromium-browser/
* https://packages.debian.org/bullseye/chromium-driver
* https://askubuntu.com/questions/1383789/install-chrome-on-ubuntu-debian-with-arm64

**Comment by Firefishy** [comment]
@saghul Nudge. Interested in this pull request? Happy to make any chances as required. Else feel free to take parts of it.

**Comment by saghul** [comment]
Sorry for the lack of a reply here. I've been a bit busy lately. Will try to get to this next week.

**Comment by saghul** [comment]
Quick update: I noticed rebasing my branch would take longer than taking yours :-) So I'm adding the missing parts to make builds with the Makefile and I'll refactor the release process to use buildx and we should be good to go.

**Comment by saghul** [comment]
Question, what's that commit about the cache?

**Comment by saghul** [comment]
Thanks! We have our first unstable builds with arm64 now :-) Thanks a lot!

**Pull request merged**
