### PR TITLE
Publish nightly the unstable tag 

### PR DESCRIPTION
**Pull request by hrenard**
Hi,
This solve #908. 
[Workflow demo](https://github.com/hrenard/docker-jitsi-meet/actions/runs/530524485)
Need to add 3 secrets to the repository : 
- DOCKERHUB_USERNAME (jitsi)
- DOCKERHUB_TOKEN
- JITSI_REPO (jitsi)

### CODE REVIEW

**Comment by saghul** [comment]
Looks great, thank you! I need to take a second look, since I think your change will break release.sh at the moment.

**Comment by saghul** [comment]
Also, I wonder if we should tag this with unstable-YYYY-MM-DD ?

**Comment by hrenard** [comment]
Thanks. 

I tried to minimize changes on the existing stuff. If I understood correctly, images are always built on top of the latest base (or base-java) image. The BASE_TAG that I introduce has latest value by default, so it shouldn’t break anything. But tell me if I’m mistaken.

It’s a good question, I’m not sure there is real a benefice of keeping such history. I think people should use the unstable build to try out the latest features but if they want to stick to a specific version, it should be a release.

**Comment by saghul** [comment]
> It’s a good question, I’m not sure there is real a benefice of keeping such history. I think people should use the unstable build to try out the latest features but if they want to stick to a specific version, it should be a release.

I think there is definitely some value in being able to tell "something works in unstable-XXX but not in unstable-YYY".

**Comment by hrenard** [comment]
Okay, I'll add this change.

**Comment by hrenard** [comment]
I added the dated tag. Tell me if I need to change something else.

**Comment by pierreozoux** [comment]
@saghul do you need help to get this moving? it would be an amazing addition :)

Thanks for your time!

**Comment by saghul** [comment]
It's close to the top of my list, I just haven't gotten around it yet, sorry!

**Comment by saghul** [comment]
Sorry it took some time. Landed now, let's see if I set it up correctly :-)

**Comment by saghul** [comment]
I ran the job manually for the first time and we now have the first batch of unstable tags. Thanks a lot @hrenard !

**Pull request merged**
