### PR TITLE
Enable A/V Moderation

### PR DESCRIPTION
**Pull request by khakulov**
With enviroment variable ENABLE_AV_MODERATION will be av_moderation enabled

### CODE REVIEW

**Comment by saghul** [comment]
I tested this and I'm getting the following error:

```
prosody_1  | avmoderation.meet.jitsi:av_moderation_component              warn	No room found found for /folkshipsslideobviously
```

Looks like the room name has a preceding / which is making this not work perhaps? Are you aware of this bug @damencho ?

**Comment by khakulov** [comment]
https://github.com/jitsi/docker-jitsi-meet/blob/856e414084876551fe29f0c72d54d476d9905bd0/env.example#L221

but `util.lib.lua` uses `conference` by default, so that `muc_mapper_domain` is `conference.jitsi.meet`.
https://github.com/jitsi/jitsi-meet/blob/9914a5d14a9ede95fbbd9674a38401ed24bd1fa1/resources/prosody-plugins/util.lib.lua#L11

i have added new enviroment variable XMPP_MUC_DOMAIN_PREFIX, so that `muc_mapper_domain` should be correct

**Comment by damencho** [comment]
> I tested this and I'm getting the following error:
> 
> ```
> prosody_1  | avmoderation.meet.jitsi:av_moderation_component              warn	No room found found for /folkshipsslideobviously
> ```
> 
> Looks like the room name has a preceding / which is making this not work perhaps? Are you aware of this bug @damencho ?

Nope. It works on alpha ...

**Comment by saghul** [comment]
> https://github.com/jitsi/docker-jitsi-meet/blob/856e414084876551fe29f0c72d54d476d9905bd0/env.example#L221
> 
> 
> 
> but `util.lib.lua` uses `conference` by default, so that `muc_mapper_domain` is `conference.jitsi.meet`.
> 
> https://github.com/jitsi/jitsi-meet/blob/9914a5d14a9ede95fbbd9674a38401ed24bd1fa1/resources/prosody-plugins/util.lib.lua#L11
> 
> 
> 
> i have added new enviroment variable XMPP_MUC_DOMAIN_PREFIX, so that `muc_mapper_domain` should be correct

Good catch!

**Comment by wernf** [comment]
Thanks for this patch.

I am wondering: would we add the av_moderation_component pending on the value of ENABLE_AV_MODERATION? It might not do any harm adding unused configuration, it would just make the config cleaner. But maybe I am missing something.

**Comment by saghul** [comment]
> Thanks for this patch.
> 
> I am wondering: would we add the av_moderation_component pending on the value of ENABLE_AV_MODERATION? It might not do any harm adding unused configuration, it would just make the config cleaner. But maybe I am missing something.

Makes sense. @khakulov can you please guard the component?

**Comment by khakulov** [comment]
> Makes sense. @khakulov can you please guard the component?

done

**Comment by saghul** [comment]
Squashed and landed in c95f0d6, thanks @khakulov ! I ended up scrapping XMPP_MUC_DOMAIN_PREFIX, since we can infer it from XMPP_MUC_DOMAIN, as we do when generating the config file.

**Pull request closed without merging**
