### PR TITLE
YAML scripts used to deploy on Kubernetes

### PR DESCRIPTION
**Pull request by jmereaux**
A set of YAML scripts that can be used as a starting point for deploying Jitsi Meet on a Kubernetes cluster

### CODE REVIEW

**Comment by sapkra** [comment]
Is there any plan to merge this PR. It's open since more than one month.

**Comment by reimertz** [comment]
Hey all, I have been trying to get this to work over at Google Cloud Engine, but it seems they don't support LoadBalancer consuming both UDP and TCP. 

Anyone who have solved this or have suggestions to get it to work?

It seems I might have to follow [this](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/tcp-udp) example inorder to get it to work but seems way more complicated that I want it to be. :(

**Comment by sapkra** [comment]
@reimertz 
I'm using the NodePort instead. In my case it's working maybe also in yours.

This is my service:
```yaml
apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jitsi
    name: jvb
  spec:
    type: NodePort
    ports:
    - name: udp
      port: 10000
      protocol: UDP
      targetPort: 10000
    - name: tcp
      port: 10000
      protocol: TCP
      targetPort: 10000
    selector:
      service: jvb
```

**Comment by reimertz** [comment]
@sapkra Thank you, will try this. Really appreciate it! 

Did you have to do any other specific tweaks to get it to work? Manually open up ports etc? It seems I cannot get the videobridge to properly connect with users. :(

**Comment by sapkra** [comment]
The `NodePort` is opening automatically the port on all nodes.
I'm not using any ingress because I'm using OpenShift/OKD so I can add a `Route` instead which is basically a HA-Proxy but I'm only using it for the  `web` container.

Maybe you forgot to set the `DOCKER_HOST_ADDRESS` to your cluster **IP address**.

Additionally I'm using the environment variables of the service in the `sip-communicator.properties` of jvb. Maybe they are named differently in you environment. You can check those with `printenv | grep _SERVICE_` in the terminal of your pod.
```properties
org.jitsi.videobridge.SINGLE_PORT_HARVESTER_PORT={{ .Env.JVB_UDP_SERVICE_PORT }}
org.jitsi.videobridge.TCP_HARVESTER_PORT={{ .Env.JVB_TCP_SERVICE_PORT }}
```

**Comment by sapkra** [comment]
I refactored my configs and now I notices that the service config I posted has some problems.

More information you can find here:
https://community.jitsi.org/t/how-is-the-videobridge-connected/16524

**Comment by reimertz** [comment]
Thank you for updating me. Sadly, the more time I spend on this, the more I feel like I might lack the appropriate knowledge to be able to resolve issues quickly. (mainly working as a App / Web Developer). 

For example, deploying these yaml-files to Google Cloud Engine, I'll have to ssh into each container to tweak settings. There's gotta be a better way of doing it. Have you publish your own docker images with appropriate settings so you don't have to ssh into each container to tweak?

Secondly, I seem to not be able to simply verify that that udp / tcp ports are properly open using ncat. No communication seem to be possible. Been looking at Firewall settings but all seems good.  So another specific setting somewhere I am missing somewhere. 

It seems I'll have to wait for someone who knows that they do who got Jitsi to work on GKE.

**Comment by sapkra** [comment]
1. Yeah I have published by own images but I want to merge a lot of my changes step by step into this repository. One reason I'm doing it is that I need some features like JWT authentication and OpenShift is running the containers with random user IDs so I have to fix the permissions in each container. So I'm doing nothing special.
2. You can use Environment Variables & ConfigMap to change the values.

Here are some tricks:
1. Use ConfigMaps to define the environment variables so you don't have duplicated configs.
 The same is also possible with Secrets.

```yaml
kind: ConfigMap
  apiVersion: v1
  metadata:
    labels:
      app: jitsi
    name: jitsi-config
  data:
    XMPP_DOMAIN: jitsi.example.com
    ...
```

In your Deployment you can use `envFrom` instead of `env`
```yaml
- envFrom:
  - configMapRef:
      name: jitsi-config
```

2. You can set the value of the service environment variable as the value of the predefined jitsi variables. That means you don't have to change the config files itself. Please note that this method is not working in ConfigMaps.

```yaml
- env:
  - name: XMPP_SERVER
    value: $(PROSODY_SERVICE_HOST)
  - name: JVB_PORT
    value: $(JVB_SERVICE_PORT_UDP)
  - name: JVB_TCP_PORT
    value: $(JVB_SERVICE_PORT_TCP)
  - name: XMPP_BOSH_URL_BASE
    value: http://$(PROSODY_SERVICE_HOST):$(PROSODY_SERVICE_PORT_5280)
```

Note: I'm refactoring my configs right now so that I don't have to change the original files anymore. I did it before but it was not the cleanest solution. You can also do it if you want by mounting a ConfigMap as a volume and use the file name as the key/name for the entries. Just have a look at the ConfigMap documentation.

**Comment by aaronkvanmeerten** [comment]
Hi, thanks for the work here, I hope to get this merged shortly!  Sorry for the delayed review.

**Comment by shamalco** [comment]
Hi, deployed successfully to our environment, just had to edit service to match our environment. Thank you for the manifests, I hope its gets merged soon. 

Are you considering to make helm repo for deployment, that would even make it easier to deploy ?

**Comment by sapkra** [comment]
There already is a branch for the helm chart.

**Comment by aaronkvanmeerten** [comment]
Yes, there is a branch with a very basic helm chart.  We hope to instrument the values.yaml with all the options from docker-compose before publishing a repo.  Then we can update the chart as part of our CI pipeline.  This may not happen for a few months based on the rest of our teams schedule and commitments.

**Comment by saghul** [comment]
I'm closing this for now. A PR shall be opened when ready. For anyone reading, the current work in progress can be seen here: https://github.com/jitsi/docker-jitsi-meet/tree/k8s-helm

Thanks everyone!

**Comment by MansM** [comment]
is there any progress on this. With all the corona I have heared from some companies their video conferencing solutions are breaking down and would like to provide my team with an alternative

**Comment by dimm0** [comment]
https://github.com/jitsi/docker-jitsi-meet/tree/dev/examples/kubernetes
Not sure why it's still in dev branch, and not master...

**Comment by Zempashi** [comment]
@MansM, @dimm0 you may want to give a try to https://github.com/jitsi/docker-jitsi-meet/pull/235. Comments welcome ;)

**Comment by dimm0** [comment]
I prefer not to use helm

**Comment by Zempashi** [comment]
@dimm0 you don't helm for "installing", you can:
```
helm template jitsi k8s/helm/ --output-dir manifests
```
And then use your favorite tool to deploy manifests. But if you don't want to you helm at all, that not really helpful, I know...

I wanted include a `manifests` directory, but I don't know the options to choose, I can't predict the domain name of people, neither the different network settings...

**Comment by saghul** [comment]
FWIW I just merged dev onto master.

**Comment by brunobarros** [comment]
Hi,

Is there an YAML example to expose the webapp with NodePort, instead of Ingress?

**Pull request closed without merging**
