### PR TITLE
Adds a check for certbot's success and exits in case of a failure

### PR DESCRIPTION
**Pull request by funkyfuture**

### CODE REVIEW

**Comment by saghul** [comment]
I think a better fix would be to `set -e` for the script. Whatever fails we want the whole thing to fail...

**Comment by funkyfuture** [comment]
i agree. but i'd leave the pausing for the mentioned reasons in place. that okay?

**Comment by saghul** [comment]
Makes sense. The `-e` is a follwop-up change that should be applied everywhere really.

**Comment by saghul** [comment]
Thank you!

**Comment by funkyfuture** [comment]
thank you for maintaining!

**Pull request merged**
