### PR TITLE
allow to configure shutdown api

### PR DESCRIPTION
**Pull request by cinques**
#1141

### CODE REVIEW

**Comment by cinques** [comment]
Ok
Added

**Comment by xoxys** [comment]
Side note: This was a breaking change, as it looks like the default config on older releases has the colobri API enabled by default. We had to enable it again explicitly now to get our monitoring working again, while if it was working without a special config before. 

It is also not the best way to mix two features (Shutdown API/Colibir API) into one PR without any hint in the PR description. Makes it hard do search :)

**Comment by f-asa** [comment]
@xoxys how did you fixed it ? you re-enable the --apis=${JVB_ENABLE_APIS:="none"} options for the api ?

**Comment by f-asa** [comment]
and what is the Shutdown API ?

**Comment by xoxys** [comment]
No, there are two new Env vars now to control the API's and `JVB_ENABLE_APIS` was removed,see https://github.com/jitsi/docker-jitsi-meet/blob/master/env.example#L406-L408

**Pull request merged**
