### PR TITLE
Example Traefik v2

### PR DESCRIPTION
**Pull request by ruby232**
Change the Traefik example to version 2

### CODE REVIEW

**Comment by SebastianKobs** [comment]
Wouldn't it be better, to add the traeffk v2 docker-compose.yml as a separate file? Me and others are still running on 1.7.

**Comment by sapkra** [comment]
This was his first approach: https://github.com/jitsi/docker-jitsi-meet/pull/313
My thoughts on this were: I don't know the traefik community but if someone is still using an older version he can still look at the file history.

**Comment by SebastianKobs** [comment]
"Someone" is an understatement. The migration from v1.7 to v2 is not trivial if you have a large number of hosts or projects to upgrade. Traefik 1.7.24 is still actively maintained and available as an official image. So my votes still goes to keeping both examples.

**Comment by ruby232** [comment]
@SebastianKobs I agree, but really i don't know what do..
* Reopen #313?
Please let me know

**Comment by saghul** [comment]
Looks like a 1.7 releasse was made just 5 days ago: https://github.com/containous/traefik/releases/tag/v1.7.24 Let's have both then.

**Pull request closed without merging**
