### PR TITLE
Improve wording of README.md

### PR DESCRIPTION
**Pull request by frispete**
My first little contribution. Hope, you like it..

### CODE REVIEW

**Comment by sapkra** [comment]
Can you please fix the same wording issues in the `.env` file too? 🙂

**Comment by frispete** [comment]
> Thank you for the contribution.

With pleasure. I would love to contribute to this valuable project in these times. Just consider this a warm-up. Hopefully getting my [issues](#294) sorted out soon, I'm ready to provide more valuable contributions. An example of integrating with an existing nginx/certbot infrastructure is first and foremost here.

> Can you please fix the same wording issues in the `.env` file too? :slightly_smiling_face:

Given, you had `env.example` in mind, here we go...

While at it, I'm inclined to remove the trailing full stops from `env.example`, but that would produce some churn. Opinions?

**Comment by sapkra** [comment]
> While at it, I'm inclined to remove the trailing full stops from env.example, but that would produce some churn. Opinions?

I also think they are quite annoying, but @saghul has to decide that.

**Comment by saghul** [comment]
Thanks @frispete ! Regarding full-stops, I like docs to be gramatiaclly correct! :-)

**Comment by sapkra** [comment]
@saghul But these are no sentences, but rather headings, which grammatically have no full-stops.

**Comment by frispete** [comment]
Thanks for the merge, @saghul. 

While I really support your request of being grammatically correct, it's rather disturbing for casual readers due to attempting to make fragments of sentences **look** correct, while they are not.

**Pull request merged**
