### PR TITLE
synology spk v.0.5

### PR DESCRIPTION
**Pull request by TosoBoso**
Hi Jitsi team,
I created under folder examples-synology a SPK package wrapped around docker-jitsi-meet for conveniant install and run on that NAS device, It is a standalone setup using the jitsi-meet images and compose files adding start-stop cli scripts and a GUI control. 
Kindly asking you to review and merge in the pull request.
-TosoBoso

### CODE REVIEW

**Comment by saghul** [comment]
Hey there, thanks for contibuting this! Why is it necessary to copy all Docker compose files? That has the Danger of going out of sync very quickly. May I suggest you use some "prepare.sh" script to copy them from a release?

**Comment by TosoBoso** [comment]
Hi, followed advised and removed the copy of compose files. All bundled in v.0.7 with other enhancements.
Note using the original compose files has a down side, that if new etc-directories to be mounted come into play the code in this SPK has to be reworked, but better compatibility issues early in the process. I moved the etc-dirs to be created into a lib-cfg file. 
PS: you should consider adding to the compose files  container_name and hostname making it look nicer and predictable (container name is otherwise derived from etc working directory and hostname is cryptic). I leave this up to you but in my scripts I'm pimping the compose files while keeping linked to the uptream.

**Comment by TosoBoso** [comment]
Hi, I now provided a followup up version v0.8 with more enhancements and would love to share with wider audience.
Can you advise if/when you consider merging in and let me know if a cricial part is missing or incompatible with the main package stream?

**Comment by TosoBoso** [comment]
Hi Gabriel, 
assuming you are using the current version 0.8 pushed to my fork in Github (not yet visible in docker-jitsi) and published as signed package here: https://www.cphub.net/?p=jitsimeet

Ad. 1.) I need to have a look at it, currently my testing was with internal authentication only. I nwe function introduced: when you do a refresh the latest Docker environment .env file is taken from Github and then a function env2env is invoked carrying over all your settings in .env, So if you had AUTH_TYPE=jwt set it should survive and not get into internal (unless commented out). When you do a reset equally the /etc/jitsi is cleaned up and built new based on the .env you have and see in GUI via Docker Environment. So I'm struggling to recreate the issue but try to work with your hints as it was working in previous version 06/07. 
Can you tell me how your .env looks like for AUTH section once you run refresh (what gets lost)? BTW the old version of .env is preserved in original (use original button to restore)?

Ad 2.): as outlined in install GUI Jibri is experimental. I also have it in FAQ: currently it will not run on Synology Docker given the ALSO loopback dependency. I kept it bundled in the package as an orchestration option for future use when issue 721 is resolved (https://github.com/jitsi/docker-jitsi-meet/issues/721)

- Volker aka TosoBoso

**Comment by gpopesc** [comment]
Thank you very Volker. You give me an idea where the problem might be and now it is solved. :+1: 

Yes, I am using version 0.8 from cphub. In environment settings, I setup my instance on the new path (CONFIG=/volume1/docker/jitsi), where it was also the last version installed. In the new version, I had to create new folder (/prosody/config). I think in the previous version it was without final config (/prosody). For the rest of 3 docker containers there were no changes. I think the configuration files were mixed from both versions and that's why it end up with no authentication.  Now I cleared all setting from previous installation and everything went fine when I reinstall it.

JWT authentication is working fine with the settings I wrote in my first message. Rocket chat create the links using stored credentials in the program.

One general question: do you think it is possible to have both: internal and jwt authentication?

I appreciate your work for making this docker installation for jitsi meet so simple. If you need to test future fixes (like no 2) let me know and I will be happy to help.

Gabriel

**Comment by TosoBoso** [comment]
Hi Gabriel,
OK this explains it: not a bug but deviation in expected usage. I will add as feature request to the health check a warning fordeviation from CONFIG=/etc/jitsi in .env
If you are using your own config directory some of the essential features of the package are broken incl. deleting and recreating config sub-directories.
Volker aka TosoBoso

**Comment by saghul** [comment]
Hey there. I think this example is way too involved for us to adopt. I think it's best if you keep the synology packages in a repository of your own. We can add a link to it on the examples README, how does this sound?

**Comment by TosoBoso** [comment]
Hi Saghul, I understand your rational and am OK with it, respectively with the link in examples readme. However I would still prefer a full merge in examples for transparency. Considering in examples it is stated own risk maintained by others you do not need to be in too deep and your advise using global env/yaml was well received and implemented. 
Well let's start with a link and you might discuss internally if to merge it in later. I expect with version 1.0 the update rate will calm down a bit and I'm happy to do a walthrough for the Synology SPK specifics with one of you.
Volker aka TosoBoso

**Comment by saghul** [comment]
Gotcha. Ok, let's start with the separate repo and a link and let's see how far it takes us. Feel free to either change this PR or make a new one. Cheers!

**Comment by TosoBoso** [comment]
Hi there the link for examples docker-jitsi-meet to synology SPK in my forked repo was never created. 
I find this disappointing. I will for sure not delete my fork and continue to work on the Jitsi-Meet Docker Synology package as it evolved a wide interest. I will BTW port to DSM7 in beta and it will be one of the 3rd party packages early birds Synology Docker packages. I would love to share it with wider audience givign oppertunity to contribute. The code is fully segregated into examples so I cannot see any invasive issue.
Let me know if you are interested in new PRs; I'm already reaching version 1.0 with DSM7 support running low-privileged. 
-TosoBoso

**Comment by dkonanjp** [comment]
**Dear TosoBoso,**
I installed the last version of JitsiMeet V 0.9 on my Synology DS218+ with RAM = 10 GO
Only the default option and in my browser (Firefox, with **https:192.168.x.xx:8443**) the message showed is below.


image


And in the same browser with **192.168.x.xx:8080**, i see the right page.
So when i want to make videoconfrence this page below appear.

image

Please can you help me?
Best regards

**NAS Synoloy DS 218+
RAM: 10 GO**

**Pull request closed without merging**
