### PR TITLE
Add example traefik v2

### PR DESCRIPTION
**Pull request by ruby232**

### CODE REVIEW

**Comment by saghul** [comment]
Thank you! Why do we need another one? Can’t the existing one be updated?

**Comment by ruby232** [comment]
I've added a new one because if someone's still using Traefik 1.

**Comment by saghul** [comment]
I don't know much about Traefik, but unless v1 is stilll supported and somewhat of an LTS, I'd say we only want to have examples for the latest 
.

**Comment by ruby232** [comment]
OK, I'm going to create a new pull request.

**Comment by saghul** [comment]
Oh, I can't reopen. Can you make a new PR again please? Sorry for the trouble.

**Comment by ruby232** [comment]
@saghul not problem

**Pull request closed without merging**
