### PR TITLE
prosody: fix restart loop on rolling deployment

### PR DESCRIPTION
**Pull request by sapkra**
This PR is the revive of the reverted PR #190. The permission problem should be fixed now.

@saghul Should I change the path like you commented here? https://github.com/jitsi/docker-jitsi-meet/pull/190#issuecomment-589728732
I could try using the default `/var/run/prosody/prosody.pid`. WDYT?

FYI: This PR is currently based on #192.

### CODE REVIEW

**Comment by saghul** [comment]
re-targeted for master, you caught me mid-change, I'm deprecating the dev branch and cutting out a release today, if things go ok.

**Comment by saghul** [comment]
> I could try using the default `/var/run/prosody/prosody.pid`. WDYT?

Makes sense!

**Comment by saghul** [comment]
Alright, I'm going to give this a test, thanks a lot for this @sapkra !

**Comment by saghul** [comment]
Just a cosmetic thing: is there a way to make this look a bit better? `I have no name!@25b911148469:/$` :-)

**Comment by saghul** [comment]
Just gave it a quick test and things look good! Nice work!

**Comment by sapkra** [comment]
> > I could try using the default `/var/run/prosody/prosody.pid`. WDYT?
> 
> Makes sense!

I will try that. Then I will not need the permission change anymore I guess.



> Just a cosmetic thing: is there a way to make this look a bit better? `I have no name!@25b911148469:/$` :-)

That's part of #192. I've chosen the user 1001 because it's default and also the OpenShifts docs are saying that I should use a numeric user. But what I will do is dynamically adding the user ID to the passwd and assigning a username.

### OpenShift Docs
Lastly, the final `USER` declaration in the `Dockerfile` should specify the user ID (numeric value) and not the user name. This allows OpenShift Container Platform to validate the authority the image is attempting to run with and prevent running images that are trying to run as root, because running containers as a privileged user exposes potential security holes.
https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#use-uid

**Comment by sapkra** [comment]
Closing this because everything should be fixed in #192 now.

**Pull request closed without merging**
