### PR TITLE
ci: dryrun docker builds on PRs

### PR DESCRIPTION
**Pull request by xoxys**
Made a first draft. Not sure what about `secrets.JITSI_REPO`. Can we make this secret available for PRs as well, or do we need to handle it differently for PRs?

### CODE REVIEW

**Comment by xoxys** [comment]
Seems to work this way. Let me know if you want to handle it any other way.

**Comment by saghul** [comment]
Looks pretty good! I'll take a close look shortly.

**Comment by xoxys** [comment]
@saghul any update on this PR?

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Sorry for the delay!

**Pull request merged**
