### PR TITLE
add JIGASI_SIP_PORT and JIGASI_SIP_TRANSPORT variables

### PR DESCRIPTION
**Pull request by netaskd**
Add JIGASI_SIP_PORT and JIGASI_SIP_TRANSPORT variables for a native configure sip transport and sip port.

### CODE REVIEW

**Comment by saghul** [comment]
Hey there! Some nice work here, cheers! Can you please split unrelated commits into different PRs please?

**Comment by netaskd** [comment]
Hi saghul,
I've created a new branch (pr32_jigasi) for the PR. Please change it in PR settings.

**Comment by saghul** [comment]
hey @netaskd I cannot seem to be able to change the source branch, just the target. Meybe force-push or open a new PR, that's fine too.

**Comment by netaskd** [comment]
@saghul, i've created new pr (36) with the branch. Thanks

**Comment by saghul** [comment]
Merged! As for the remaining commits, I don't particularly like the added arguments for s6 and frep versions, I think those are ok in the Dockerfile.

Can you split the TLSv1.2 patch please? I need to test if we'd be leaving out some devices, but generally it sounds good.

Thanks for your contributions!

**Comment by netaskd** [comment]
@saghul, PR (#37) with tls12 is requested.

**Pull request closed without merging**
