### PR TITLE
add(web): enableFeaturesBasedOnToken support

### PR DESCRIPTION
**Pull request by debendraoli**

### CODE REVIEW

**Comment by saghul** [comment]
@damencho did we talk about deprecating this feature or did I dream about it?

**Comment by damencho** [comment]
We had dropped part of it. But that is still available, whether UI to respect what is in the token.

**Comment by saghul** [comment]
> We had dropped part of it. But that is still available, whether UI to respect what is in the token.

Let's sync with Emil, IIRC this was meant to disappear to one point after Meet Pro was sidelined.

**Comment by damencho** [comment]
People from jaas are also using it, so doubt that to be dropped.

**Comment by saghul** [comment]
After discussing with @damencho, the plan is to axe the setting altogether: https://github.com/jitsi/jitsi-meet/pull/12028

**Comment by debendraoli** [comment]
Looks good then.

**Pull request closed without merging**
