### PR TITLE
Refresh prosody dockerfile

### PR DESCRIPTION
**Pull request by benbz**
This updates https://github.com/jitsi/docker-jitsi-meet/compare/master...matrix-org:jaywink/prosody-image-http-module against a newer upstream base and minimises how much we need to build

### CODE REVIEW

**Comment by benbz** [comment]
Sorry, I incorrectly targetted this repo from a fork

**Comment by saghul** [comment]
Hey, we'll be glad to take improvements Matrix needs :-)

**Comment by benbz** [comment]
Heh, that's always good to hear, thanks!

We've a [pair of modules](https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification) that currently use the lua `http` library, which is what we have forked this repo for. As per https://github.com/matrix-org/docker-jitsi-meet/pull/1 it may be that we remove the need for that dependency and so we can use these images. If the dependency doesn't go away, I'm happy to submit a PR to include the `http` library here, if you think it has value for yourself / others.

**Comment by saghul** [comment]
I think it would be good if Matrix users can use our Docker images unchanged, just by configuring the needed modules with ENV variables (already possible) proven we have the necessary dependencies. This would help users get the latest and greatest versions and you folks not needing to maintain a fork.

**Pull request closed without merging**
