### PR TITLE
prosody: update to latest stable version

### PR DESCRIPTION
**Pull request by saghul**
Use the official repositories so we don't lag behind in fixes.

### CODE REVIEW

**Comment by saghul** [comment]
@damencho @aaronkvanmeerten WDYT?

**Comment by saghul** [comment]
YOLO.

**Comment by sapkra** [comment]
@saghul I've built the master branch last night and noticed that prosody is installed from the stretch-backports which is still at version 0.11.2 but the recent prosody version is 0.11.5.

When starting the new container I got:
```bash
startup             info	Hello and welcome to Prosody version 0.11.2
```

**Comment by saghul** [comment]
Hum, I'll take a look, thanks for the heads up! I think I know the problem: the `-t stretch-backports`. I needed to add it back for lua-sec, but that undid my update. Oh well!

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/commit/93ba77021b3604df380174635a1267e01b04a18c

**Pull request merged**
