### PR TITLE
Kubernetes Setup using kustomize

### PR DESCRIPTION
**Pull request by rsoika**
Hi,

this is my suggestion of how we could improve the configuration for Kuberentes based on kustomize.

The core configuraition is placed on docker-jitsi-meet. And users can customize the setup with [Kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) declaring new objects or providing custom environment variables by overwriting the deployment.yaml file. 

I have explained the setup in the README.md file

@saghul  : Can you take a look at this and give you your feedback if it is worse to be merged?

### CODE REVIEW

**Comment by rsoika** [comment]
If you are unhappy with this pull request I can create a new one with less commits?

**Comment by prayagsingh** [comment]
@saghul @sapkra  I have a suggestion here. Instead of changing `examples/kubernetes` files, we can have sub-directories under `example/kubernetes` like `kubernetes/simple-deployment`, `kubernetes/deployment-with-kustomize` and finally `kubernetes/deployment-with-helm`. WDYT?

**Comment by rsoika** [comment]
@saghul @sapkra may I provide a new pull request using the sub-directory layout as suggested by @prayagsingh 

    /examples/kubernetes/deployment-with-kustomize

I would like to share my setup and I also would like to discuss the websocket problem I am still facing

**Comment by saghul** [comment]
@rsoika That's not the direction we'd like to follow. See #991

**Comment by rsoika** [comment]
I will provide a new pull request explaining how to fix the websocket problem

**Pull request closed without merging**
