### PR TITLE
added TCP_HARVESTER_SSLTCP control in the env file

### PR DESCRIPTION
**Pull request by mghadam**
Added control for [videobridge.ice.tcp.ssltcp](https://github.com/jitsi/jitsi-videobridge/blob/master/CONFIG.md) variable in the .env file

### CODE REVIEW

**Comment by saghul** [comment]
@bgrozev @JonathanLennox does it make sense to have this enabled by default?

**Comment by damencho** [comment]
We recommend using coturn for the TCP connections, we have seen problems with jvb cpu usage when the tcp from jvb is used, that's why that is turned off by default as it is not recommended to be used.

**Comment by damencho** [comment]
> > @bgrozev @JonathanLennox does it make sense to have this enabled by default?
> 
> Yes, it already defaults to `true`. This is the option to pretent to use SSL, not the option to enable/disable the TCP harvester.

Ups :) Sorry.

**Comment by saghul** [comment]
Sorry this fell trough the cracks. We have completely disabled TCP support in the JVB so this no longer applies, sorry.

**Pull request closed without merging**
